name = "DebuggableTests"
uuid = "b1683bb7-a3c7-4730-bfe9-b1642477e304"
authors = ["knttnk <61683744+knttnk@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
